# Generated by Django 5.2.4 on 2025-07-30 03:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('letra', models.CharField(default='A', max_length=1)),
                ('ultimo_numero', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_turno', models.CharField(max_length=10, unique=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('llamado', 'Llamado'), ('atendiendo', 'Atendiendo'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('fecha_atencion', models.DateTimeField(blank=True, null=True)),
                ('fecha_finalizacion', models.DateTimeField(blank=True, null=True)),
                ('cliente', models.ForeignKey(limit_choices_to={'rol': 4}, on_delete=django.db.models.deletion.CASCADE, related_name='tickets_como_cliente', to=settings.AUTH_USER_MODEL)),
                ('notaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='app.notaria')),
                ('operador', models.ForeignKey(blank=True, limit_choices_to={'rol': 3}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_como_operador', to=settings.AUTH_USER_MODEL)),
                ('tipo_servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tipoticket')),
            ],
            options={
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['tipo_servicio', 'estado'], name='app_ticket_tipo_se_465f08_idx'), models.Index(fields=['notaria', 'estado'], name='app_ticket_notaria_a0a8aa_idx')],
            },
        ),
    ]
